export enum SIDES {
  BUY = 'BUY',
  SELL = 'SELL'
}

export enum TYPES {
  MARKET= 'MARKET',
  LIMIT= 'LIMIT',
  STOP= 'STOP',
  STOP_MARKET= 'STOP_MARKET',
  TAKE_PROFIT= 'TAKE_PROGIT',
  TAKE_PROFIT_MARKET= 'TAKE_PROFIT_MARKET'
}